name: Build

on:	
  workflow_dispatch:  
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:	
  build:	
    runs-on: ubuntu-latest	

    steps:	
    - uses: actions/checkout@master	

    - name: Set up Node.js version	
      uses: actions/setup-node@v1	
      with:	
        node-version: '12.x'	

    - name: npm install, build, and test	
      run: |	
        npm install	
        npm run build --if-present	
